name: react-native-android-build-apk
on:
  push:
    branches:
      - main
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

Evet projemizi tamamladık şimdi github üzerine pushlayarak actions log’ları inceleyelim.

https://github.com/akaramanapp/StoreApp/actions adresine girerek job’ları görüntüleyebiliriz.

Commit işlemimizin ardından her iki job’da çalışarak görevleri tamamlamış oldugunu görüyoruz. (Artifacts kısmına bakarsanız apk dosyamızın da yüklendiğini göreceksiniz.)

Detay Log:

Bir sonraki makalede görüşmek dileğiyle.. Hoşça kalın.
React Native
Github Actions
Android
Continuous Integration
Continuous Deployment

